name: arenoapp
description: "Areno Express - Logistics Management Mobile App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  lottie: ^3.1.0

  # State Management
  provider: ^6.1.1
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9

  # Firebase
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  firebase_storage: ^12.4.10
  firebase_messaging: ^15.2.10

  # Maps & Location
  google_maps_flutter: ^2.12.3
  geolocator: ^14.0.2
  geocoding: ^4.0.0

  # HTTP & API
  http: ^1.1.2
  dio: ^5.4.0

  # Local Storage
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Image & File Handling
  image_picker: ^1.0.4
  file_picker: ^10.2.0
  path_provider: ^2.1.1

  # UI Components
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.0
  photo_view: ^0.15.0

  # Navigation
  go_router: ^16.0.0

  # Utilities
  intl: ^0.20.2
  url_launcher: ^6.2.2
  permission_handler: ^12.0.1
  device_info_plus: ^11.5.0

  # Notifications
  flutter_local_notifications: ^19.3.1

  # QR Code
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.0.1

  # Charts
  fl_chart: ^1.0.0

  # Camera
  camera: ^0.11.2
  flutter_launcher_icons: ^0.14.4
  convex_bottom_bar: ^3.2.0
  animated_notch_bottom_bar: ^1.0.3
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  google_sign_in: ^7.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/arenologisticslogo.png
    - assets/icons/
    - assets/animations/

flutter_icons:
  android: true
  ios: false
  image_path: "android/app/icon-temp/logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "android/app/icon-temp/logo.png"
